name: Use Our Service

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to our workflow
        uses: sakura-intern25-group-f/hako-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}