on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Deploy to Sakura AppRun
        uses: meso/sakura-apprun-action@v3
        with:
          sakura-api-key: ${{ secrets.SAKURA_API_KEY }}
          sakura-api-secret: ${{ secrets.SAKURA_API_SECRET }}
          container-registry: ${{ vars.SAKURACR_REGISTRY }}
          container-registry-user: ${{ secrets.SAKURACR_USER }}
          container-registry-password: ${{ secrets.SAKURACR_PASSWORD }}
